<?php
	$colors = array(
		array('nom' => 'Black', 'codi' => '#000000'),
		array('nom' => 'Navy', 'codi' => '#000080'),
		array('nom' => 'DarkBlue', 'codi' => '#00008B'),
		array('nom' => 'MediumBlue', 'codi' => '#0000CD'),
		array('nom' => 'Blue', 'codi' => '#0000FF'),
		array('nom' => 'DarkGreen', 'codi' => '#006400'),
		array('nom' => 'Green', 'codi' => '#008000'),
		array('nom' => 'Teal', 'codi' => '#008080'),
		array('nom' => 'DarkCyan', 'codi' => '#008B8B'),
		array('nom' => 'DeepSkyBlue', 'codi' => '#00BFFF'),
		array('nom' => 'DarkTurquoise', 'codi' => '#00CED1'),
		array('nom' => 'MediumSpringGreen', 'codi' => '#00FA9A'),
		array('nom' => 'Lime', 'codi' => '#00FF00'),
		array('nom' => 'SpringGreen', 'codi' => '#00FF7F'),
		array('nom' => 'Aqua', 'codi' => '#00FFFF'),
		array('nom' => 'Cyan', 'codi' => '#00FFFF'),
		array('nom' => 'MidnightBlue', 'codi' => '#191970'),
		array('nom' => 'DodgerBlue', 'codi' => '#1E90FF'),
		array('nom' => 'LightSeaGreen', 'codi' => '#20B2AA'),
		array('nom' => 'ForestGreen', 'codi' => '#228B22'),
		array('nom' => 'SeaGreen', 'codi' => '#2E8B57'),
		array('nom' => 'DarkSlateGray', 'codi' => '#2F4F4F'),
		array('nom' => 'DarkSlateGrey', 'codi' => '#2F4F4F'),
		array('nom' => 'LimeGreen', 'codi' => '#32CD32'),
		array('nom' => 'MediumSeaGreen', 'codi' => '#3CB371'),
		array('nom' => 'Turquoise', 'codi' => '#40E0D0'),
		array('nom' => 'RoyalBlue', 'codi' => '#4169E1'),
		array('nom' => 'SteelBlue', 'codi' => '#4682B4'),
		array('nom' => 'DarkSlateBlue', 'codi' => '#483D8B'),
		array('nom' => 'MediumTurquoise', 'codi' => '#48D1CC'),
		array('nom' => 'Indigo', 'codi' => '#4B0082'),
		array('nom' => 'DarkOliveGreen', 'codi' => '#556B2F'),
		array('nom' => 'CadetBlue', 'codi' => '#5F9EA0'),
		array('nom' => 'CornflowerBlue', 'codi' => '#6495ED'),
		array('nom' => 'MediumAquaMarine', 'codi' => '#66CDAA'),
		array('nom' => 'DimGray', 'codi' => '#696969'),
		array('nom' => 'DimGrey', 'codi' => '#696969'),
		array('nom' => 'SlateBlue', 'codi' => '#6A5ACD'),
		array('nom' => 'OliveDrab', 'codi' => '#6B8E23'),
		array('nom' => 'SlateGray', 'codi' => '#708090'),
		array('nom' => 'SlateGrey', 'codi' => '#708090'),
		array('nom' => 'LightSlateGray', 'codi' => '#778899'),
		array('nom' => 'LightSlateGrey', 'codi' => '#778899'),
		array('nom' => 'MediumSlateBlue', 'codi' => '#7B68EE'),
		array('nom' => 'LawnGreen', 'codi' => '#7CFC00'),
		array('nom' => 'Chartreuse', 'codi' => '#7FFF00'),
		array('nom' => 'Aquamarine', 'codi' => '#7FFFD4'),
		array('nom' => 'Maroon', 'codi' => '#800000'),
		array('nom' => 'Purple', 'codi' => '#800080'),
		array('nom' => 'Olive', 'codi' => '#808000'),
		array('nom' => 'Gray', 'codi' => '#808080'),
		array('nom' => 'Grey', 'codi' => '#808080'),
		array('nom' => 'SkyBlue', 'codi' => '#87CEEB'),
		array('nom' => 'LightSkyBlue', 'codi' => '#87CEFA'),
		array('nom' => 'BlueViolet', 'codi' => '#8A2BE2'),
		array('nom' => 'DarkRed', 'codi' => '#8B0000'),
		array('nom' => 'DarkMagenta', 'codi' => '#8B008B'),
		array('nom' => 'SaddleBrown', 'codi' => '#8B4513'),
		array('nom' => 'DarkSeaGreen', 'codi' => '#8FBC8F'),
		array('nom' => 'LightGreen', 'codi' => '#90EE90'),
		array('nom' => 'MediumPurple', 'codi' => '#9370D8'),
		array('nom' => 'DarkViolet', 'codi' => '#9400D3'),
		array('nom' => 'PaleGreen', 'codi' => '#98FB98'),
		array('nom' => 'DarkOrchid', 'codi' => '#9932CC'),
		array('nom' => 'YellowGreen', 'codi' => '#9ACD32'),
		array('nom' => 'Sienna', 'codi' => '#A0522D'),
		array('nom' => 'Brown', 'codi' => '#A52A2A'),
		array('nom' => 'DarkGray', 'codi' => '#A9A9A9'),
		array('nom' => 'DarkGrey', 'codi' => '#A9A9A9'),
		array('nom' => 'LightBlue', 'codi' => '#ADD8E6'),
		array('nom' => 'GreenYellow', 'codi' => '#ADFF2F'),
		array('nom' => 'PaleTurquoise', 'codi' => '#AFEEEE'),
		array('nom' => 'LightSteelBlue', 'codi' => '#B0C4DE'),
		array('nom' => 'PowderBlue', 'codi' => '#B0E0E6'),
		array('nom' => 'FireBrick', 'codi' => '#B22222'),
		array('nom' => 'DarkGoldenRod', 'codi' => '#B8860B'),
		array('nom' => 'MediumOrchid', 'codi' => '#BA55D3'),
		array('nom' => 'RosyBrown', 'codi' => '#BC8F8F'),
		array('nom' => 'DarkKhaki', 'codi' => '#BDB76B'),
		array('nom' => 'Silver', 'codi' => '#C0C0C0'),
		array('nom' => 'MediumVioletRed', 'codi' => '#C71585'),
		array('nom' => 'IndianRed', 'codi' => '#CD5C5C'),
		array('nom' => 'Peru', 'codi' => '#CD853F'),
		array('nom' => 'Chocolate', 'codi' => '#D2691E'),
		array('nom' => 'Tan', 'codi' => '#D2B48C'),
		array('nom' => 'LightGray', 'codi' => '#D3D3D3'),
		array('nom' => 'LightGrey', 'codi' => '#D3D3D3'),
		array('nom' => 'PaleVioletRed', 'codi' => '#D87093'),
		array('nom' => 'Thistle', 'codi' => '#D8BFD8'),
		array('nom' => 'Orchid', 'codi' => '#DA70D6'),
		array('nom' => 'GoldenRod', 'codi' => '#DAA520'),
		array('nom' => 'Crimson', 'codi' => '#DC143C'),
		array('nom' => 'Gainsboro', 'codi' => '#DCDCDC'),
		array('nom' => 'Plum', 'codi' => '#DDA0DD'),
		array('nom' => 'BurlyWood', 'codi' => '#DEB887'),
		array('nom' => 'LightCyan', 'codi' => '#E0FFFF'),
		array('nom' => 'Lavender', 'codi' => '#E6E6FA'),
		array('nom' => 'DarkSalmon', 'codi' => '#E9967A'),
		array('nom' => 'Violet', 'codi' => '#EE82EE'),
		array('nom' => 'PaleGoldenRod', 'codi' => '#EEE8AA'),
		array('nom' => 'LightCoral', 'codi' => '#F08080'),
		array('nom' => 'Khaki', 'codi' => '#F0E68C'),
		array('nom' => 'AliceBlue', 'codi' => '#F0F8FF'),
		array('nom' => 'HoneyDew', 'codi' => '#F0FFF0'),
		array('nom' => 'Azure', 'codi' => '#F0FFFF'),
		array('nom' => 'SandyBrown', 'codi' => '#F4A460'),
		array('nom' => 'Wheat', 'codi' => '#F5DEB3'),
		array('nom' => 'Beige', 'codi' => '#F5F5DC'),
		array('nom' => 'WhiteSmoke', 'codi' => '#F5F5F5'),
		array('nom' => 'MintCream', 'codi' => '#F5FFFA'),
		array('nom' => 'GhostWhite', 'codi' => '#F8F8FF'),
		array('nom' => 'Salmon', 'codi' => '#FA8072'),
		array('nom' => 'AntiqueWhite', 'codi' => '#FAEBD7'),
		array('nom' => 'Linen', 'codi' => '#FAF0E6'),
		array('nom' => 'LightGoldenRodYellow', 'codi' => '#FAFAD2'),
		array('nom' => 'OldLace', 'codi' => '#FDF5E6'),
		array('nom' => 'Red', 'codi' => '#FF0000'),
		array('nom' => 'Fuchsia', 'codi' => '#FF00FF'),
		array('nom' => 'Magenta', 'codi' => '#FF00FF'),
		array('nom' => 'DeepPink', 'codi' => '#FF1493'),
		array('nom' => 'OrangeRed', 'codi' => '#FF4500'),
		array('nom' => 'Tomato', 'codi' => '#FF6347'),
		array('nom' => 'HotPink', 'codi' => '#FF69B4'),
		array('nom' => 'Coral', 'codi' => '#FF7F50'),
		array('nom' => 'Darkorange', 'codi' => '#FF8C00'),
		array('nom' => 'LightSalmon', 'codi' => '#FFA07A'),
		array('nom' => 'Orange', 'codi' => '#FFA500'),
		array('nom' => 'LightPink', 'codi' => '#FFB6C1'),
		array('nom' => 'Pink', 'codi' => '#FFC0CB'),
		array('nom' => 'Gold', 'codi' => '#FFD700'),
		array('nom' => 'PeachPuff', 'codi' => '#FFDAB9'),
		array('nom' => 'NavajoWhite', 'codi' => '#FFDEAD'),
		array('nom' => 'Moccasin', 'codi' => '#FFE4B5'),
		array('nom' => 'Bisque', 'codi' => '#FFE4C4'),
		array('nom' => 'MistyRose', 'codi' => '#FFE4E1'),
		array('nom' => 'BlanchedAlmond', 'codi' => '#FFEBCD'),
		array('nom' => 'PapayaWhip', 'codi' => '#FFEFD5'),
		array('nom' => 'LavenderBlush', 'codi' => '#FFF0F5'),
		array('nom' => 'SeaShell', 'codi' => '#FFF5EE'),
		array('nom' => 'Cornsilk', 'codi' => '#FFF8DC'),
		array('nom' => 'LemonChiffon', 'codi' => '#FFFACD'),
		array('nom' => 'FloralWhite', 'codi' => '#FFFAF0'),
		array('nom' => 'Snow', 'codi' => '#FFFAFA'),
		array('nom' => 'Yellow', 'codi' => '#FFFF00'),
		array('nom' => 'LightYellow', 'codi' => '#FFFFE0'),
		array('nom' => 'Ivory', 'codi' => '#FFFFF0'),
		array('nom' => 'White', 'codi' => '#FFFFFF')
	);
?>
<!doctype html>
<html>
<head>
	<meta charset="utf8"/>
</head>
<body>
	<div>
		<table>
			<tr>
			<?php
				foreach($colors as $i=>$c){		
			?>
				<td bgcolor="<?=$c['codi']?>"><?=$c['nom']?></td>
			<?php
				if(($i+1)%3==0){
			?>
					</tr><tr>
			<?php
				}
			?>	
			<?php
				}
			?>

		</p>
	</div>
</body>
</html>